### ISSUE TITLE
Merge some PRs, update to Rspec 3

### ISSUE THREAD

**Issue by eoinkelly** [michaeldv/awesome_print#164]
Hi there,
I have: 
* updated the specs to run under Rspec 3 syntax
* merged PR #161 #158 #153 #151 #38 #38 #145 
* Make all specs pass for latest versions of extensions gems:
    * ActiveRecord  4.0.4
    * ActiveSupport 4.0.4
    * MongoMapper   0.13.0
    * Mongoid       4.0.0
    * ActionView    4.0.4
    * Ripple seems to be abandoned so no changes made.  http://basho.com/tag/ripple-client-apis/

I'm guessing you want to put most of your energy into the rewrite but it would be great to get some of the small stuff fixed in master until the rewrite is done. 

As per your README, here i the link to the comparison. I can make PR if you need too.

https://github.com/eoinkelly/awesome_print/compare/michaeldv:master...master

Thanks for making a super useful gem!

cheers

/Eoin/

**Comment by eoinkelly** [comment]
LGTM :sparkles:

**Comment by maurogeorge** [comment]
Closing, since this as solved.
