### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by maurogeorge** [michaeldv/awesome_print#174]
@imajes or @michaeldv only you guys have power to do that.

Please follow the [2 first steps of this guide](http://docs.travis-ci.com/user/getting-started/).

The [.travis.yml](https://github.com/michaeldv/awesome_print/blob/master/.travis.yml) is already in place.

**Comment by maurogeorge** [comment]
@michaeldv any feedback on that? :grimacing:

**Comment by michaeldv** [comment]
@maurogeorge @imajes I've set it up, please check https://travis-ci.org/michaeldv/awesome_print

**Comment by maurogeorge** [comment]
@michaeldv thanks man! 

Closing since was fixed.
