### ISSUE TITLE
Back in Action!

### ISSUE THREAD

**Issue by jfelchner** [michaeldv/awesome_print#178]
Super glad to see that @michaeldv has delegated maintenance of this fine gem to people who will advance it.  No shame in that!  Can't wait to see what's in store for awesome print to make it more awesomer!

:heart: :heart: :heart: :heart: :heart: :heart:

**Comment by nviennot** [comment]
yay!!!

:heart:

**Comment by maurogeorge** [comment]
:heart: to more awesome objects on ruby :100: 

Closing since this is no issue :smile:
