### ISSUE TITLE
Generating an awesome string? (to_awesome)

### ISSUE THREAD

**Issue by mahemoff** [michaeldv/awesome_print#195]
Is there a way to get this working like `inspect` or `to_s`, e.g. `puts "Result: #{some_object.to_awesome}"`?

**Comment by mahemoff** [comment]
Here's a quick attempt that works for me. I suppose it would be better with some options hash but I haven't looked into the classes in question.

    class Object
      def awesome
        AwesomePrint::Formatter.new(AwesomePrint::Inspector.new).format self
      end
    end

**Comment by D-side** [comment]
Yep, it's called `ai`:

![](http://i.imgur.com/W1dUuGr.png)

**Comment by michaeldv** [comment]
Yes, and `ai` is an alias for `awesome_inspect`

**Comment by mahemoff** [comment]
Nice to know. Thanks.
