### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by mediafinger** [michaeldv/awesome_print#198]
I just started working on an app that does not have awesome_print in its Gemfile - and than I realized (again) how much I miss the awesomeness, when I can't have it.

Thanks for making my life as a Ruby / Rails developer a little bit happier each day :rainbow: 

PS: I am teaching a bunch of aspiring devs next week - and I will show them the difference of normal to awesome output :smile:

**Comment by michaeldv** [comment]
You are very welcome :-)
