### ISSUE TITLE
Is there a way to use awesome_print as string?

### ISSUE THREAD

**Issue by georgeu2000** [michaeldv/awesome_print#214]
If you have a method that returns a string, is it possible to use awesome_print to return the formatted string?

For example,

    def error_for hash
       "There was an error for this hash: " + ...
    end

**Comment by otherthing** [comment]
Looking at the [kernel method](https://github.com/michaeldv/awesome_print/blob/master/lib/awesome_print/core_ext/kernel.rb), the `ap` method uses the `ai` internally.

So to get the returned value of `ap ["object"]` you would write `["object"].ai`

You can pass options as an argument to `ai`

This returns ASCII encoded text, i.e. the example above returned `"[\n    \e[1;37m[0] \e[0m\e[0;33m\"object\"\e[0m\n]"`

If you want to render this on an HTML page I recommend the Javsacript library [ansi_up](https://github.com/drudru/ansi_up)

I agree that this should be documented, though, i will submit a pull request

**Comment by MaxPleaner** [comment]
Looking at the kernel method, the ap method uses the ai internally.

So to get the returned value of ap ["object"] you would write ["object"].ai

You can pass options as an argument to ai

This returns ASCII encoded text, i.e. the example above returned "[\n \e[1;37m[0] \e[0m\e[0;33m\"object\"\e[0m\n]"

If you want to render this on an HTML page I recommend the Javsacript library ansi_up

I agree that this should be documented, though, i will submit a pull request

**Comment by michaeldv** [comment]
@MaxPleaner, try this:
```
irb> puts ["object"].ai(html: true)
<pre>[
    <kbd style="color:white">[0] </kbd><kbd style="color:brown">&quot;object&quot;</kbd>
]</pre>
```
or
```
irb> ap ["object"], html: true
<pre>[
    <kbd style="color:white">[0] </kbd><kbd style="color:brown">&quot;object&quot;</kbd>
]</pre>
```

**Comment by georgeu2000** [comment]
Great. Thank you.
